on:
  workflow_call:
    
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: npm ci
    - run: npm run test
