on:
  workflow_call:
    inputs:
      artifact-name:
        required: true
        type: string
      branch:
        required: true
        type: string
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: npm ci
    - run: npm run build
  build-badge:
    needs: main
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: peterrhodesdev/build-a-badge@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: build-${{ inputs.branch }}
          label: Build
          message: ${{ (needs.main.result == 'success' && 'passing' ) || 'failing' }}
          color: ${{ (needs.main.result == 'success' && 'success' ) || 'critical' }}
        