on:
  workflow_call:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Comparing develop changesets against current changes
      id: list_changesets
      run: |
        if [[ -d .changeset ]]; then
          git fetch
          git checkout origin/develop
          CHANGESETS_DEV=$(ls -lA .changeset/*.md | awk '{print $9}')
          echo "origin/develop changesets: $CHANGESETS_DEV"

          git checkout $GITHUB_SHA

          CHANGESETS_CURRENT=$(ls -lA .changeset/*.md | awk '{print $9}')
          echo "$GITHUB_REF changesets: $CHANGESETS_CURRENT"
          NEW_CHANGESET=1
          for CURRENT_MD in $CHANGESETS_CURRENT; do
            echo "> $CURRENT_MD"
            echo "$CHANGESETS_DEV" | grep -o "$CURRENT_MD" || NEW_CHANGESET=0
          done
          
          if [[ "$NEW_CHANGESET" != "0" ]]; then
            echo "Please add a changeset by running npm run version:changeset"
            exit 1
          fi
        else 
          echo ".changeset directory does not exists"
        fi
    