on:
  workflow_call:
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - run: |
        apt install jq
        GIT_MAIN_BRANCH="origin/main"
        GIT_CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)

        # Retrieves old version
        git checkout $GIT_MAIN_BRANCH
        VERSION_OLD=$(cat package.json | jq -r '.version')

        # Retrieves new version
        git checkout $GIT_CURRENT_BRANCH
        VERSION_NEW=$(cat package.json | jq -r '.version')

        if [[ "$VERSION_OLD" = "$VERSION_NEW" ]]; then
          echo "please bump package.json version"
          exit 1
        else echo "package.json version is up to date"
        fi

        cat CHANGELOG.md | grep -o "## $VERSION_NEW"

        if [[ "$?" = "0" ]]; then
          echo "CHANGELOG.md seems to have changes"
          exit 0
        else
          echo "please add changes to the CHANGELOG.md file"
          exit 1
        fi
