on:
  workflow_call:
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Retrieve package.json version
        id: version
        run: |
          PKG_VERSION=$(npm pkg get version --workspaces=false | tr -d \")
          echo "PKG_VERSION=$PKG_VERSION" >> "$GITHUB_OUTPUT"
      - name: Tags new version
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          commit_sha: ${{ github.sha }}
          custom_tag: ${{ steps.version.outputs.PKG_VERSION }}
          tag_prefix: v
    outputs:
      version: ${{ steps.version.outputs.PKG_VERSION }}
  create-release:
    needs: create-tag
    runs-on: ubuntu-latest
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          commitish: ${{ github.sha }}
          tag_name: "v${{ needs.create-tag.outputs.version }}"
          release_name: "Release v${{ needs.create-tag.outputs.version }}"
          draft: false
          prerelease: false
