# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Develop

on:
  push:
    branches: [ "dev", "develop" ]
  pull_request:
    branches: [ "dev", "develop" ]

jobs:
  check-changelog:
    uses: ./.github/workflows/check-changelog.yml
  test:
    uses: ./.github/workflows/test.yml
    with:
      branch: develop
  build:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      branch: develop
