# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Develop

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  check-changeset:
    uses: ./.github/workflows/check-changeset.yml
  test:
    uses: ./.github/workflows/test.yml
    with:
      branch: dev
  build:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      artifact-name: ${{ github.sha }}
      branch: dev
  # publish:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   steps:
  #     - name: publish pkg
  #       run: exit 0
        
