# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Main

on:
  push:
    branches: [ "main" ]

jobs:
  check-changelog:
    uses: ./.github/workflows/check-changelog.yml
  test:
    uses: ./.github/workflows/test.yml
    with:
      branch: main
  build:
    needs: test
    uses: ./.github/workflows/build.yml
    with:
      branch: main
  build-artifacts:
    needs: build
    uses: ./.github/workflows/build-artifacts.yml
    with:
      artifact-name: ${{ github.sha }}
      branch: main
