# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Publish

on:
  push:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: ${{ github.repository }}
    - run: echo 1
    # uses: iolave/nombrerutyfirma/.github/workflows/buildAndPublishDockerImage.yml@main
  test-other:
    uses: ${{ github.repository }}/.github/workflows/test.yml
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: npm ci
    - run: npm run build
    - run: npm prune --production
    - name: Upload artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{ github.sha }}
        path: |
          ./dist
          ./package.json
          ./package-lock.json
          ./node_modules
  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: publish pkg
        run: exit 0
        
