on:
  workflow_call:
    inputs:
      branch:
        required: true
        type: string
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
    - run: npm ci
    - run: npm run test
  build-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: peterrhodesdev/build-a-badge@v1.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filename: test-${{ inputs.branch }}
          label: my
          message: badge